name: Matrix Example

on:
  push:
    paths:
      - .github/workflows/matrix.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]  # as many versions we provide here, that many times the job will run
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
